# Site settings
title: Applied Optimal
email: info@appliedoptimal.ca
description: > # this means to ignore newlines until "baseurl:"
  Applied Optimal - Website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Applied Optimal
email: info@appliedoptimal.ca
facebook_username:
twitter_username:
github_username:
address:
  - line: Lethbridge, AB
  # - line: AB
  # Feel free to add more lines here 
telephone:
copyright: Applied Optimal

# API settings
google_api_key:

# Build settings
markdown: kramdown
remote_theme: 

include: ["_pages"]